import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import List, Dict
from datetime import datetime
import json
from pathlib import Path
import hashlib


class EmailNotifier:
    """Sends email notifications for new job listings."""
    
    def __init__(self, smtp_server: str = "smtp.gmail.com", smtp_port: int = 587):
        self.smtp_server = smtp_server
        self.smtp_port = smtp_port
        self.seen_jobs_file = Path("seen_jobs.json")
        self.seen_jobs = self._load_seen_jobs()
    
    def _load_seen_jobs(self) -> set:
        """Load previously seen job IDs."""
        if self.seen_jobs_file.exists():
            with open(self.seen_jobs_file, "r") as f:
                data = json.load(f)
                return set(data.get("seen_ids", []))
        return set()
    
    def _save_seen_jobs(self):
        """Save seen job IDs."""
        with open(self.seen_jobs_file, "w") as f:
            json.dump({"seen_ids": list(self.seen_jobs)}, f)
    
    def _generate_job_id(self, job: Dict) -> str:
        """Generate unique ID for a job."""
        key = f"{job.get('title', '')}{job.get('company', '')}{job.get('url', '')}"
        return hashlib.md5(key.encode()).hexdigest()
    
    def get_new_jobs(self, jobs: List[Dict]) -> List[Dict]:
        """Filter out jobs we've already seen."""
        new_jobs = []
        for job in jobs:
            job_id = self._generate_job_id(job)
            if job_id not in self.seen_jobs:
                new_jobs.append(job)
                self.seen_jobs.add(job_id)
        
        self._save_seen_jobs()
        return new_jobs
    
    def format_email_body(self, jobs: List[Dict], subject: str = None) -> str:
        """Format jobs into HTML email body."""
        if not subject:
            subject = f"🚀 New Agentic AI Engineer Jobs - {datetime.now().strftime('%Y-%m-%d')}"
        
        html = f"""
<!DOCTYPE html>
<html>
<head>
    <style>
        body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
        .container {{ max-width: 800px; margin: 0 auto; padding: 20px; }}
        .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); 
                   color: white; padding: 30px; border-radius: 10px; margin-bottom: 20px; }}
        .job-card {{ background: #f8f9fa; border-left: 4px solid #667eea; 
                     padding: 20px; margin-bottom: 15px; border-radius: 5px; }}
        .job-title {{ font-size: 18px; font-weight: bold; color: #667eea; margin-bottom: 5px; }}
        .company {{ font-size: 16px; color: #555; margin-bottom: 10px; }}
        .skills {{ background: #667eea; color: white; padding: 3px 10px; 
                   border-radius: 15px; font-size: 12px; display: inline-block; margin: 2px; }}
        .requirements {{ margin-top: 10px; }}
        .requirements li {{ margin-bottom: 5px; }}
        .cta-button {{ background: #667eea; color: white; padding: 12px 25px; 
                       text-decoration: none; border-radius: 5px; display: inline-block; 
                       margin-top: 10px; }}
        .footer {{ text-align: center; color: #888; font-size: 12px; margin-top: 30px; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🤖 New Agentic AI Engineer Jobs</h1>
            <p>Found {len(jobs)} new opportunities matching your criteria</p>
        </div>
"""
        
        for i, job in enumerate(jobs, 1):
            skills_html = ""
            for skill in job.get("skills", [])[:5]:
                skills_html += f'<span class="skills">{skill}</span>'
            
            requirements_html = ""
            for req in job.get("requirements", [])[:3]:
                requirements_html += f"<li>{req}</li>"
            
            html += f"""
        <div class="job-card">
            <div class="job-title">{i}. {job.get('title', 'Unknown Position')}</div>
            <div class="company">🏢 {job.get('company', 'Unknown Company')}</div>
            <div>📍 {job.get('location', 'Not specified')} | 🌐 {job.get('source', 'Unknown')}</div>
            <div style="margin-top: 10px;">{skills_html}</div>
            {f'<div class="requirements"><strong>Requirements:</strong><ul>{requirements_html}</ul></div>' if requirements_html else ''}
            {f'<a href="{job.get("url", "#")}" class="cta-button">View Job</a>' if job.get('url') else ''}
        </div>
"""
        
        html += f"""
        <div class="footer">
            <p>Generated by Agentic AI Job Search Agent | {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        </div>
    </div>
</body>
</html>
"""
        return html
    
    def send_email(self, sender_email: str, sender_password: str, 
                   recipient_email: str, jobs: List[Dict], 
                   subject: str = None) -> bool:
        """Send job notification email."""
        if not jobs:
            print("No new jobs to notify about.")
            return False
        
        if not subject:
            subject = f"🚀 {len(jobs)} New Agentic AI Engineer Jobs - {datetime.now().strftime('%Y-%m-%d')}"
        
        # Create message
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = sender_email
        msg["To"] = recipient_email
        
        # HTML content
        html_content = self.format_email_body(jobs, subject)
        msg.attach(MIMEText(html_content, "html"))
        
        try:
            # Send email
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(sender_email, sender_password)
                server.sendmail(sender_email, recipient_email, msg.as_string())
            
            print(f"✅ Email sent to {recipient_email} with {len(jobs)} jobs")
            return True
            
        except Exception as e:
            print(f"❌ Failed to send email: {e}")
            return False
    
    def send_digest(self, sender_email: str, sender_password: str,
                    recipient_email: str, jobs: List[Dict]) -> bool:
        """Send a daily digest email."""
        subject = f"📋 Daily Digest: {len(jobs)} Agentic AI Engineer Jobs - {datetime.now().strftime('%Y-%m-%d')}"
        return self.send_email(sender_email, sender_password, recipient_email, jobs, subject)
